name: Check the source code

run-name: ${{ github.actor }} is running GitHub Actions 🚀

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Install-packages:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install

  Prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettier
        run: npm run format
  ESLint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - name: Lint
        run: npm run lint